version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: concert-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: concert_db
      MYSQL_USER: concert_user
      MYSQL_PASSWORD: concert_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database-setup.sql:/docker-entrypoint-initdb.d/database-setup.sql
    networks:
      - concert-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: 
      context: ./main_backend
      dockerfile: Dockerfile
    container_name: concert-backend
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/concert_db
      SPRING_DATASOURCE_USERNAME: concert_user
      SPRING_DATASOURCE_PASSWORD: concert_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: docker
      JAVA_OPTS: "-Xmx512m -Xms256m"
    ports:
      - "8080:8080"
    networks:
      - concert-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      start_period: 60s
      retries: 3

volumes:
  mysql_data:

networks:
  concert-network:
    driver: bridge
